// PL lang variables utf-8
// ***********************************************************************
// ** Title.........:    TinyMCE polish lang. Plugins: table
// ** Version.......:    1.0
// ** Author........:    Stefan Wajda <zwiastun@zwiastun.net>,
// ** Filename......:    pl.js (polish language file)
// ** Last changed..:    13/06/2006, 6.05.2011
// ***********************************************************************/
tinyMCE.addToLang('table',{
general_tab : 'Podstawowe',
advanced_tab : 'Rozszerzone',
general_props : 'Podstawowe właściwości',
advanced_props : 'Rozszerzone właściwości',
desc : 'Wstaw nową tabelę',
row_before_desc : 'Wstaw wiersz powyżej',
row_after_desc : 'Wstaw wiersz poniżej',
delete_row_desc : 'Usuń wiersz',
col_before_desc : 'Wstaw kolumnę przed',
col_after_desc : 'Wstaw kolumnę za',
delete_col_desc : 'Usuń kolumnę',
rowtype : 'Wiersz w części tabeli',
title : 'Wstaw/Dostosuj tabelę',
width : 'Szerokość',
height : 'Wysokość',
cols : 'Kolumny',
rows : 'Wiersze',
cellspacing : 'Odstęp&nbsp;między komórkami',
cellpadding : 'Odstęp&nbsp;wewnątrz komórek',
border : 'Krawędzie',
align : 'Wyrównanie',
align_default : 'Domyślnie',
align_left : 'Do lewej',
align_right : 'Do prawej',
align_middle : 'Wyśrodkuj',
row_title : 'Właściwości wiersza',
cell_title : 'Właściwości komórki',
cell_type : 'Typ komórki',
row_desc : 'Właściwości wiersza',
cell_desc : 'Właściwości komórki',
valign : 'Wyrównanie pionowe',
align_top : 'Do góry',
align_bottom : 'Do dołu',
props_desc : 'Właściwości tabeli',
bordercolor : 'Kolor obramowania',
bgcolor : 'Kolor tła',
merge_cells_title : 'Scal komórki',
split_cells_desc : 'Podziel komórkę',
merge_cells_desc : 'Scal komórki',
cut_row_desc : 'Wytnij wiersz',
copy_row_desc : 'Kopiuj wiersz',
paste_row_before_desc : 'Wklej wiersz powyżej',
paste_row_after_desc : 'Wklej wiersz poniżej',
id : 'ID',
style: 'Styl CSS',
langdir : 'Kierunek tekstu',
langcode : 'Kod języka',
mime : 'Typ MIME',
ltr : 'Od lewej do prawej',
rtl : 'Od prawej do lewej',
bgimage : 'Obrazek tła',
summary : 'Streszczenie',
td : "Dane",
th : "Nagłówek",
cell_cell : 'Dostosuj bieżącą komórkę',
cell_row : 'Dostosuj wszystkie komórki w rzędzie',
cell_all : 'Dostosuj wszystkie komórki w tabeli',
row_row : 'Dostosuj bieżący wiersz',
row_odd : 'Dostosuj nieparzyste wiersze',
row_even : 'Dostosuj parzyste wiersze',
row_all : 'Dostosuj wszystkie wiersze',
thead : 'Nagłówek tabeli',
tbody : 'Korpus tabeli',
tfoot : 'Stopka tabeli',
del : 'Usuń tabelę',
scope : 'Zakres',
row : 'Wiersz',
col : 'Kolumna',
rowgroup : 'Grupuj wiersze',
colgroup : 'Grupuj kolumny',
col_limit : 'Osiągnięto maksymalną liczbę kolumn {$cols}.',
row_limit : 'Osiągnięto maksymalną liczbę wierszy {$rows}.',
cell_limit : 'Osiągnięto maksymalną liczbę komórek {$cells}.',
missing_scope: 'Czy na pewno chcesz kontynuować bez określenia zakresu komórek obejmowanych nagłówkiem. Bez podania tej informacji zrozumienie zawartości tabeli może być trudne np. dla osób niewidzących, korzystających ze specjalistycznego oprogramowania odczytującego treść tabeli.',
caption : 'Podpis tabeli'
});
